export const RESOURCE_FOUND = "RESOURCE_FOUND";
export const NO_RESOURCE_FOUND = "NO_RESOURCE_FOUND";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CONNECTION_ERROR = "CONNECTION_ERROR";
export const SERVER_ERROR = "SERVER_ERROR";

/* Book action types */
export const BOOK_COVER_ADD_SUCCESSFUL = "BOOK_COVER_ADD_SUCCESSFUL";
export const BOOK_COVER_ADD_FAILED = "BOOK_COVER_ADD_FAILED"; 
export const BOOK_COVER_REMOVE_SUCCESSFUL = "BOOK_COVER_REMOVE_SUCCESSFUL";
export const BOOK_COVER_REMOVE_FAILURE = "BOOK_COVER_REMOVE_FAILURE";

export const BOOK_ADD_SUCCESSFUL = "BOOK_ADD_SUCCESSFUL";
export const BOOK_ADD_FAILURE = "BOOK_ADD_FAILURE";

export const BOOK_LOAD_SUCCESSFUL = "BOOK_LOAD_SUCCESSFUL";
export const BOOK_LOAD_FAILURE   = "BOOK_LOAD_FAILURE";

export const CLEAR_BOOK_CACHE = "CLEAR_BOOK_CACHE";

export const BOOK_EDIT_SUCCESSFUL = "BOOK_EDIT_SUCCESSFUL";
export const BOOK_EDIT_FAILURE = "BOOK_EDIT_FAILURE";

export const ADDING_AUTHOR_TO_BOOK_SUCCESS = "ADDING_AUTHOR_TO_BOOK_SUCCESS";
export const ADDING_AUTHOR_TO_BOOK_FAILURE = "ADDING_AUTHOR_TO_BOOK_FAILURE";

export const MODIFYING_AUTHORS_IN_ONE_BOOK_SUCCESS = "MODIFYING_AUTHORS_IN_ONE_BOOK_SUCCESS";
export const MODIFYING_AUTHORS_IN_ONE_BOOK_FAILURE = "MODIFYING_AUTHORS_IN_ONE_BOOK_FAILURE";

export const ALL_BOOKS_LOAD_SUCCESSFUL = "ALL_BOOKS_LOAD_SUCCESSFUL";
export const ALL_BOOKS_LOAD_FAILURE = "ALL_BOOKS_LOAD_FAILURE";

export const ALL_BOOKS_CLEAR_SUCCESSFUL = "ALL_BOOKS_CLEAR_SUCCESSFUL";
export const ALL_BOOKS_CLEAR_FAILURE = "ALL_BOOKS_CLEAR_FAILURE";

export const BOOK_DELETE_SUCCESSFUL = "BOOK_DELETE_SUCCESSFUL";
export const BOOK_DELETE_FAILURE = "BOOK_DELETE_FAILURE";


/* Author action types */
export const AUTHOR_IMAGE_ADD_SUCCESSFUL = "AUTHOR_IMAGE_ADD_SUCCESSFUL";
export const AUTHOR_IMAGE_ADD_FAILURE = "AUTHOR_IMAGE_ADD_FAILURE";

export const AUTHOR_IMAGE_REMOVE_SUCCESSFUL = "AUTHOR_IMAGE_REMOVE_SUCCESSFUL";
export const AUTHOR_IMAGE_REMOVE_FAILURE = "AUTHOR_IMAGE_REMOVE_FAILURE";

export const AUTHOR_ADD_SUCCESSFUL = "AUTHOR_ADD_SUCCESSFUL";
export const AUTHOR_ADD_FAILURE = "AUTHOR_ADD_FAILURE";

export const AUTHOR_LOAD_SUCCESSFUL = "AUTHOR_LOAD_SUCCESSFUL";
export const AUTHOR_LOAD_FAILURE   = "AUTHOR_LOAD_FAILURE";

export const CLEAR_AUTHOR_CACHE = "CLEAR_AUTHOR_CACHE";

export const AUTHOR_EDIT_SUCCESSFUL = "AUTHOR_EDIT_SUCCESSFUL";
export const AUTHOR_EDIT_FAILURE = "AUTHOR_EDIT_FAILURE";

export const ALL_AUTHORS_LOAD_SUCCESSFUL = "ALL_AUTHORS_LOAD_SUCCESSFUL";
export const ALL_AUTHORS_LOAD_FAILURE = "ALL_AUTHORS_LOAD_FAILURE";

export const ALL_AUTHORS_CLEAR_SUCCESSFUL = "ALL_AUTHORS_CLEAR_SUCCESSFUL";
export const ALL_AUTHORS_CLEAR_FAILURE = "ALL_AUTHORS_CLEAR_FAILURE";

export const ADDING_BOOK_TO_AUTHOR_SUCCESS = "ADDING_BOOK_TO_AUTHOR_SUCCESS";
export const ADDING_BOOK_TO_AUTHOR_FAILURE = "ADDING_BOOK_TO_AUTHOR_FAILURE";

export const MODIFYING_BOOKS_IN_ONE_AUTHOR_SUCCESS = "MODIFYING_BOOKS_IN_ONE_AUTHOR_SUCCESS";
export const MODIFYING_BOOKS_IN_ONE_AUTHOR_FAILURE = "MODIFYING_BOOKS_IN_ONE_AUTHOR_FAILURE";

export const AUTHOR_DELETE_SUCCESSFUL = "AUTHOR_DELETE_SUCCESSFUL";
export const AUTHOR_DELETE_FAILURE = "AUTHOR_DELETE_FAILURE";